[[Patchelf]]
arch = "aarch64"
git-tree-sha1 = "26e0521e8539d8e23c6829edda4d8d8934f27f18"
os = "macos"

    [[Patchelf.download]]
    sha256 = "2347de2a1f6f49156e477c8e11d3421a076f450d12e3d4b7b5f4cf8996f9b943"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.aarch64-apple-darwin.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29bcd9edd3cf9f3f44d5e8061411e853aec903b8"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "cc892de13519d7d84b0f2b3b7dfbc1b217def24c4ffb856dd678d1ed17a6d352"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a1eed95e8c8c1ef291ba9173d5e27560bbcf374"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "bfc9ca26af5ab97cbf96d018ca88b017fcfec5ff41f1bcaf0b1a58d3dfe43aee"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45e7081b3764d1cd4d9bc091ce4d7c66be52d9c1"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "fb252c0bf27e51854a31740ac4e20a3a882debb9200f3d2a7ceb1dadd7b8105d"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.aarch64-linux-musl-cxx03.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd33fa829312021d49314ca300b4d5a6797a81e5"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "5ea02d957522cb9cfbea40815f6749bcfbf8987a11335f1e1b281bd449cc97bd"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.aarch64-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f7005f6d06f46ef1fabf7b249b04c17240fde37"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "57633afa6f59ff4b124b16025ac42683c23dfd0f2eccfd5226af4d3c86725c4a"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ae246a7793d1321caa0e3ce65d3334d099c7325"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "563cd9d3aef96e0d80f6f5e4dcc2d38dc83f62a9b9e5158886efb184e8491806"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5158904ec85e6242d14ec48b0a2d6daa5d68f8f"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "4ec9ee06a2c9a2f02a29fbf6f511694af123f1ce51c2cc2c8376f054d45adfc8"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e21ec455e55c851eb527ecd852709749c1fa2ba"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "6ff5018f0f952b06241e9a284dd99c95eb806870f4802018a985c13c37bc13dd"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8241b89d2bc502d70bae4387301d4ebde9030db"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "981d301203367820ca433e0a498e158e7febc8b757e681505d21760eb02ceeab"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3105d5752735cdd39339943d493b1d94233204c"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "f4a4468000116eef0d417486b473c7eb8b2186b84c8c182f12a76eaea4d6a45f"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "962382ca4f27a48de4a55dc17887f52ec913ea72"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "0917d4e0d6251ef4e01bbcf2ae99d3d53926317a50c5878bdf4ff84642f07c60"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f833e93602460819307c46a3cd840dcdab62b455"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "32fe6bd90067480d247237a22624f4447e46349c99ebc57f27b6c607f895cbdb"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39ed71ad6a6c2049bb3864fb1072699fc2ecfc02"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "7faa20b52ba865bb0459d4438796f84c970357195837dd9a7a458a3d3dcdf303"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.i686-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9621038437a822c2e403614b52ae4a1cccab62d"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "ab576ee531eac479272a38db1a1f40afe1ee4ba56d7dd634349a1b3a2f224de9"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.i686-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b989848348833630931ac161cacba96da74c46f8"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "8e6be9b43a6cddba1dbaca0c334d8502461ff3b94a6d3d8c9672cc71b2764f54"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.i686-linux-musl-cxx03.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f65e04166e5b67d060f969822bf874a19bc23c5a"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "e6f7d36507138ae2c42c9e10dd0e67ca4226ae286c7b9e0cd45eccf44a3f8a94"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.i686-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec01717bed6c791656ec4c2b67e657f6565dc96d"
os = "windows"

    [[Patchelf.download]]
    sha256 = "2a652a191a34fbcb3cdb8c696c0f700e36b182fe0040bccceb5fdacd9767da04"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.i686-w64-mingw32-cxx03.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f62529089677a056be733c6a01ccba0c17cfc149"
os = "windows"

    [[Patchelf.download]]
    sha256 = "e22ea89d2b7bc749e6e20d1a5e92f2c69b6fdfb2fe4007bda4a6924d87744deb"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.i686-w64-mingw32-cxx11.tar.gz"
[[Patchelf]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8e2892271ae70deba2c4cf6753a68c80e09a4e2"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "711823d64330df2c2fdf78911796d5001d57e57e6f291306badd0fc3faea6533"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "977074f45ffdea529abf7076f46910693e5062ab"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "84aae5cc8669a68c56232fdcfbd183d08ac91e10f154c7797e50e6d453e04a16"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
git-tree-sha1 = "0ca3b2318dbbe2075aa51c52da071585a0cc7d8b"
os = "macos"

    [[Patchelf.download]]
    sha256 = "0c207c182628a552a54e25bc96a60b942dc250fc3b30b14071ee6e0e7a54ea5f"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-apple-darwin.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f64293ca25ab4dcd5de7fca2c24554cfe07a1603"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "3a334529f6c093a2067f761f4dbef348aa8589efeb19f453bdddf88b29598279"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "196763baeb646d66b7d9ed4c94209f7801965737"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "60a8efc7b5e6a7fb3ba5cec6430411481cce55aab4bd5765efe1dd15d98d0360"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58b88c97d0f92cadb1896fb3aa0ab928217819bc"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "9e11e5ebedadd659c3b731b2d3a667bb04a6b510016986ad94c786f828154631"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-linux-musl-cxx03.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae02336aef11ad92bc0faeb09b987bf2ee0cf5cd"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "5779357151486e9c1121a0509bd1fa7c1c9accbff2d2dab9fba33bf9c8c0215d"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
git-tree-sha1 = "5061768ee9463f559d1584e1fd2baa823037ec3c"
os = "freebsd"

    [[Patchelf.download]]
    sha256 = "c4da1279c5e595e368c9b5ccf33ec0ec21f9dbea796fb344f299c4979c1f22a6"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-unknown-freebsd.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e23008069b8ede6e457d4b3fff0649772a4de579"
os = "windows"

    [[Patchelf.download]]
    sha256 = "82f0c882cf8484d4e32c7d94938d20e9057861e97ece3f369684207c7abb0013"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e458decae332b190307b98349ffc801f26d9a9ff"
os = "windows"

    [[Patchelf.download]]
    sha256 = "036c08333d72534f36679b16a929327c0eef1a3466201ffce6cdaa7481029279"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2+0/Patchelf.v0.17.2.x86_64-w64-mingw32-cxx11.tar.gz"
