[[Patchelf]]
arch = "aarch64"
git-tree-sha1 = "7c1b66d56d372f9fc9cfd1c3a46c4b8df7c7b981"
os = "macos"

    [[Patchelf.download]]
    sha256 = "b95606823d378a62393f49ce6bdd98e212c1f6223ce547746390f05c8f414c4a"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.aarch64-apple-darwin.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4cef78b29ae8d8a9e53da6dcd1ec319132ba9d8"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "d56a42d91ca6ed7091c91b2d17ab0483485bab9e8c4ba73235bfdf1e13e0b355"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97d894343470aea802611416ea5e56cfd870e354"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "744123b5220ee8e8c682818de8f819c3e5f9c2a267ada931aa29750e4e161fdc"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.aarch64-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "aarch64"
git-tree-sha1 = "aa0d82ffc766c6a29d9d019c564c36874018ad17"
os = "freebsd"

    [[Patchelf.download]]
    sha256 = "6bfb03c6d3c4b8b9ad21c6769ba4505ba5505f1d3a634ee47e9f83aa2b5b0842"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.aarch64-unknown-freebsd.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dac5ea9c0056eb4c41066ff048b522a2149dbeb2"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "f8eaf0720dcf565886813a658d26f94a624381fd2f118e67676963e4d9333839"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdbff56f61f56eeff7f16cc2c753868182998175"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "595f63af2bd95e601b33b6093b6b6f6426e1bccc6a2fe7c7bdbe04822696b25b"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e6fc4743a08e38eaca2aa1e013442746caf73d8"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "60e5e0eaa1e681dc7324547d2f49bd9eda4e762abea0ee1c02d670ad1bbaf16a"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1043c64b6e37f732fda7fefcce20e66790a147ef"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "f8400f3488850139d92c347217b35cca203b83c863a497108d401433befa4f46"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "950b9266602fc092eb5e95f3d10f630c686c0766"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "a4b223212f1f7c2657df2269fdb4220296a81e65f7f4344bc8f7320549d50b97"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.i686-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a9ecdd3c1525a737d9c11a564c2ce1d86b4efbc"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "e0f593a9519d1abbc90ae63bc1cb4d84c7b9c3b371ee8d71574ed6c8e7975824"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.i686-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3c0d3d2062489460e2576257b453d17376fc45a"
os = "windows"

    [[Patchelf.download]]
    sha256 = "5dac416330498c0b2400deef2df203d16677fb5db6676288535f405f71a91f69"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.i686-w64-mingw32-cxx11.tar.gz"
[[Patchelf]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e086c05e0f7513e9e4d0f6a03c25810b4ffc048b"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "595a5f8ac22db52c39d21ee87ac404c257d67ca8a7125b6291ee9fb0545a4460"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "818f67c5fa18e0a89fa8e0a916cea617634f4e04"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "cef526e4c7b010f020ce0d6c1f46592aeaab7b1b5a6f495bc6ea95c64f483df8"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.riscv64-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
git-tree-sha1 = "6ecdfd2faf411ea462f7a328c305514952a4caee"
os = "macos"

    [[Patchelf.download]]
    sha256 = "32359ad0bf577a95fc9ac41a8f0ba0617ad55a1da1d85c5df65d577fde8c9b05"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.x86_64-apple-darwin.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "509d20cc24849b0af3400cd146166614db83d6aa"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "4a11b628c598c50e0a2862eca7f688be8a63f4e163050c4e2c540f2033fb21d5"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c181f2657a3eb42f1f9a5bc73c4b2d04efd0b3c4"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "6d13f8457078aff24a89d1bd3c3d05b8054144ee826f2a82f6bfb51c76a511bb"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.x86_64-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
git-tree-sha1 = "52bde94e19ee9934484880931ad4e65adf9f7ba4"
os = "freebsd"

    [[Patchelf.download]]
    sha256 = "119f53e5051ab69645349990968d568ff72fac6dd4a8e4fb56f25621c648e085"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.x86_64-unknown-freebsd.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f35db840768b7318bab595b1cddc39b06f50e51"
os = "windows"

    [[Patchelf.download]]
    sha256 = "dde8bf8d580403aea90827f4de9f934d56821ac17381905ce83d0f8a767977b1"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.18.1+0/Patchelf.v0.18.1.x86_64-w64-mingw32-cxx11.tar.gz"
