[[Patchelf]]
arch = "aarch64"
git-tree-sha1 = "06840f7c69b6bac8be9af33294f46e0c556553e6"
os = "macos"

    [[Patchelf.download]]
    sha256 = "b37528f63f4d664ae68ee3e91365d5cfb9450426c5a8e5e203e656d1421e34dc"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.aarch64-apple-darwin.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a30654a0e423b17603d54d33e6c788679a1fcb7f"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "b6eb071f7d8a7e44e22bc754c1b1289b666bf2c55a71bfb8ac7b23cf1721730f"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23af8f210293c4234499cde8e19cce8e9f3130b9"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "7d6fa2044c2196c289ef76acaf06df84ff1b27d5118b6ac8f4cb432a5caa31ba"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69bba3822a2a63ec164437012c060928780141d0"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "cb50e3530215ac52d998c59de3327ec8a9f88476722462610ce3df9fc108d98d"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.aarch64-linux-musl-cxx03.tar.gz"
[[Patchelf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05aa3ea2016e579a11851755ac962bd01dc57224"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "2ec1f161556f5ad4e6a2048c6a7075d3bce59f5f41778876a9b189dce46a7a0c"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.aarch64-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63d7ee82f395d022fe952a9ed7aec207d60e3a90"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "ab8eef50d27c1d5b868566406296c0f64376ef7b189e45e6591516cc23c9a042"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "628c66495b6f4da8ef7f44905076a333a7682dfe"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "b0ed9a14e59bf853d57e0d565f3fba5ae800ec8865c53ce6522730bfd4be2208"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "231e042f6a2990b903e853a2d6e9bca124008ca0"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "f660a65fb4ad24c23ad0f5759ca929e03d85bada2fd79716624b0f949668367d"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f59dd70e235f51b1923c8f87168b448496400c13"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "56886a0a39d7afecdff995c18a4ec62e5f4c90cc665054d1fcd25a53a5709e9f"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0458e2639e579e79f2d68eb70038fa0c5a300314"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "979a384cf77ab17d69669d744658265d9e9768df7471b0177c18858dc4c35ed9"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91bad62086585e8b7623644286b988d68f3737cc"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "238c7bb30aac458803520e9d8b52c6e49f09751c83eb03818b15523da3cdb218"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7942810d019aaf0fdb1ec0ceb2c67f015128a99"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "a4e1d7db1b259aa24af1f94d14833cadb7d9a2bf3f67ba34aa12d9fd261d9acc"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Patchelf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "488410bf657146051a05765e9aa53ae5a53eae1b"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "d4ba0e526ebc13f9960838dfe98fe5bf3448b9a99b8301213286f2b3743ca0d7"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c358c3dddf95c1e62f08301307918962bf6ebc9"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "1042ecd966f787eb3de27494dd86f95223c6e4885cc57207f84b3cdf4dc64a8d"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.i686-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c35b84f697242255f248e28f1fc14ac3f89e2f00"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "822dd013959d7f917cda2380a2b471da713905663f5dedd1d4b02b62d45ce0c1"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.i686-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b0bc7c8c7ddde6bc1e5811b28d01fcb0ac5e6c9"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "ea9db78209d4f0a029f845e4d163f87ac9cbbf636813eb0e8b251824b426e17c"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.i686-linux-musl-cxx03.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c1652c4c9026f0703864da4d050fd3cd6918707"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "b80310503641a4b1eeb18c4aa2d6caf0e28d46bc599e54d28d2c33b6401b1a03"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.i686-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb5f43f8d5c623f223922eac59e3a5c81a733264"
os = "windows"

    [[Patchelf.download]]
    sha256 = "38c18ca0b360031ecb59822bdc312b5f11f662b267b872beeea1ad0914df924a"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.i686-w64-mingw32-cxx03.tar.gz"
[[Patchelf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4face9d1241c7c18a6c67ac65e5c73d5baa81aeb"
os = "windows"

    [[Patchelf.download]]
    sha256 = "a57c3ad45c7ecdf23beff510c06edfc7e5361baa5a2879d861aac6a6c1310f82"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.i686-w64-mingw32-cxx11.tar.gz"
[[Patchelf]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75a13be92e2fc14a89a691682ee726b30f7eac04"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "6e7247035b448b62e3428ec9350ee55af377df5fee5f14b8f170b02bbb1e8ef7"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fe7713a73a24fa5d69b0ef60a8f18621ffe8748"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "464cfcc56d2fec49b4951f8fd63a3baca67113b3384c7201be0a59e27f0547df"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
git-tree-sha1 = "db2932c26f3213e0b3752d929310c3ee18b9ca74"
os = "macos"

    [[Patchelf.download]]
    sha256 = "4bb0450ae7cdf6a43080e08c58af557dce946eb00d26e23fdb54e1b1340f04e3"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-apple-darwin.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ab892d3baac351f18686649180598aa84bf38cf"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "7235677443a1dbe354a076a2893783dbc44467428a8d2a953b114c3470047b28"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e05e7562a11fb9a3243f18d46e9516bf5623634f"
libc = "glibc"
os = "linux"

    [[Patchelf.download]]
    sha256 = "ccde7bbdee6355d16ab187ffc2521dbc76713e67091a2be28315280194221cfc"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64491b51f11a57aacdf8ec50d017f37b0031c117"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "5b7ca5ca2339fc2ddeeb91ea10af56fcfb90c2abac2f8b1e6beab04fa6a8a270"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-linux-musl-cxx03.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "898d313b4cca499bfdbe452fda47b18247a472ce"
libc = "musl"
os = "linux"

    [[Patchelf.download]]
    sha256 = "7fe11b55625975255c13220ce9e4cd8d51bc3f85a9fff7654fefe47dcff78436"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-linux-musl-cxx11.tar.gz"
[[Patchelf]]
arch = "x86_64"
git-tree-sha1 = "5a4ce04395182eccf2c1c68f5bfc2b5e40118f57"
os = "freebsd"

    [[Patchelf.download]]
    sha256 = "6bfa1c9316e6810d5b5687b0c30e995a30562f1ca8becf3bb736b32a511e3f42"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-unknown-freebsd.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdf302d1346812d5d5fbdd94b99540043c82550d"
os = "windows"

    [[Patchelf.download]]
    sha256 = "11f2aa547525e1436d1b4374f2d6be0064b7d099f677de757f351b1f5eedadf5"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Patchelf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec384d1835c94c9e03e8e679b1d474951f90108a"
os = "windows"

    [[Patchelf.download]]
    sha256 = "80bb209f5b5b34ef1427cdbc279323922c591088bd23f4b39d43ba144a2e1818"
    url = "https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.14.3+0/Patchelf.v0.14.3.x86_64-w64-mingw32-cxx11.tar.gz"
